version: '3'

services:
  playit:
    image: ghcr.io/playit-cloud/playit-agent:0.15
    network_mode: host
    environment:
    - SECRET_KEY=f710ac807c3dfddb4461f18df1d003afb4fb58d614956becbb5cfbae44620ece
